version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: transformer-inspection-db
    environment:
      POSTGRES_DB: trasformer_inspection_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transformer-inspection-app
    ports:
      - "5509:5509"
    environment:
      # Override database connection to use the postgres service
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trasformer_inspection_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      # Optional: Override analysis API URL if needed
      # ANALYSIS_API_URL: http://python-analysis-api:8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
